/// <reference types="vite/client" />

/** Generated by scripts/library-plugin.ts — a LibraryManifest (see src/lib/types.ts). */
declare module 'virtual:library' {
  const manifest: unknown;
  export default manifest;
}
